# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CtcA0RJGImD3QMW8OP7gcltd4JD_8eLK
"""

```python
from flask import Flask, jsonify
import pandas as pd
import numpy as np
import re
from datetime import datetime
from urllib.parse import quote

import matplotlib
matplotlib.use('Agg')

import matplotlib.pyplot as plt

import gspread
from google.oauth2.service_account import Credentials
from gspread_dataframe import set_with_dataframe

app = Flask(__name__)

# =========================================================
# GOOGLE AUTH
# =========================================================

scope = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]

creds = Credentials.from_service_account_file(
    "service_account.json",
    scopes=scope
)

gc = gspread.authorize(creds)

# =========================================================
# HELPER FUNCTIONS
# =========================================================

def extract_day_shift(text):
    parts = str(text).split(',')

    if parts:
        date_part = parts[0].strip()
        date_subparts = date_part.split(' ')

        if len(date_subparts) > 1:
            day = date_subparts[1]
        else:
            day = "UNKNOWN_DAY"
    else:
        day = "UNKNOWN_DAY"

    return f"{day}"


def format_unavailability_slot_for_guides(slot_name_gs):
    return slot_name_gs.replace(' - ', '-')


def get_unavailability_string_from_gs(row):

    unavailable_slots = []

    day_shift_columns_gs = [
        col for col in row.index
        if 'AM' in col or 'PM' in col
    ]

    for col in day_shift_columns_gs:

        if (
            pd.notna(row[col]) and
            str(row[col]).strip().lower() == 'x'
        ):

            formatted_slot = (
                format_unavailability_slot_for_guides(col)
            )

            unavailable_slots.append(formatted_slot)

    return ','.join(unavailable_slots)


def extract_date(text):

    match = re.search(
        r'(\d{1,2})\s(\w+)\s(\w+)\s(\d{4})',
        str(text)
    )

    if match:

        day_num = match.group(1)
        indo_month = match.group(3)
        year = match.group(4)

        month_map = {
            'Januari': 'January',
            'Februari': 'February',
            'Maret': 'March',
            'April': 'April',
            'Mei': 'May',
            'Juni': 'June',
            'Juli': 'July',
            'Agustus': 'August',
            'September': 'September',
            'Oktober': 'October',
            'November': 'November',
            'Desember': 'December'
        }

        translated_month = month_map.get(
            indo_month,
            indo_month
        )

        date_str_for_parsing = (
            f"{day_num} {translated_month} {year}"
        )

        return datetime.strptime(
            date_str_for_parsing,
            '%d %B %Y'
        )

    return None


# =========================================================
# MAIN ROUTE
# =========================================================

@app.route("/", methods=["GET", "POST"])
def run_assignment():

    try:

        # =====================================================
        # DASHBOARD
        # =====================================================

        SPREADSHEET_ID = "1oYpIm7qRNS69oWxgWPVPx1eOywvOsanr2VLaH7_pnSY"
        SHEET_NAME = "DASHBOARD"

        csv_url = (
            f"https://docs.google.com/spreadsheets/d/"
            f"{SPREADSHEET_ID}/gviz/tq?tqx=out:csv&sheet={SHEET_NAME}"
        )

        dashboard = pd.read_csv(csv_url, header=1)

        dashboard = dashboard[
            dashboard["SUDAH DIKIRIM"].notna()
        ].copy()

        dashboard = dashboard[
            dashboard["SUDAH DIKIRIM"]
            .astype(str)
            .str.strip() != ""
        ]

        dashboard['DATE'] = (
            dashboard['TANGGAL & RUTE']
            .apply(extract_date)
        )

        start_date = datetime(2026, 5, 25)
        end_date = datetime(2026, 5, 31)

        dashboard = dashboard[
            (dashboard['DATE'] >= start_date) &
            (dashboard['DATE'] <= end_date)
        ].copy()

        dashboard.reset_index(drop=True, inplace=True)

        dashboard["DAY_SHIFT"] = (
            dashboard["TANGGAL & RUTE"]
            .apply(extract_day_shift)
        )

        dashboard = (
            dashboard.iloc[::-1]
            .reset_index(drop=True)
        )

        # =====================================================
        # GUIDE UNAVAILABILITY
        # =====================================================

        GS_UNAVAILABILITY_ID = "1jS8KUIYfCHAHafgibzr74GwCEBQvaObHSgoCqRiyGCA"

        GS_UNAVAILABILITY_SHEET_NAME = (
            "CHECK UNAVAILABILITY MONTHLY"
        )

        encoded_unavailability_sheet_name = quote(
            GS_UNAVAILABILITY_SHEET_NAME
        )

        csv_url_unavailability = (
            f"https://docs.google.com/spreadsheets/d/"
            f"{GS_UNAVAILABILITY_ID}"
            f"/gviz/tq?tqx=out:csv"
            f"&sheet={encoded_unavailability_sheet_name}"
        )

        unavailability_gs = pd.read_csv(
            csv_url_unavailability,
            header=16
        )

        guides_from_gs = unavailability_gs.copy()

        guides_from_gs = guides_from_gs.rename(
            columns={'Guide': 'Name'}
        )

        guides_from_gs['Rating'] = 3.0

        guides_from_gs['Unavailability'] = (
            guides_from_gs.apply(
                get_unavailability_string_from_gs,
                axis=1
            )
        )

        guides = guides_from_gs[
            ['Name', 'Rating', 'Unavailability']
        ].copy()

        # =====================================================
        # RATING
        # =====================================================

        GS_RATING_ID = (
            "1jS8KUIYfCHAHafgibzr74GwCEBQvaObHSgoCqRiyGCA"
        )

        GS_RATING_SHEET_NAME = "RATING GUIDE"

        encoded_rating_sheet_name = quote(
            GS_RATING_SHEET_NAME
        )

        csv_url_rating = (
            f"https://docs.google.com/spreadsheets/d/"
            f"{GS_RATING_ID}"
            f"/gviz/tq?tqx=out:csv"
            f"&sheet={encoded_rating_sheet_name}"
        )

        ratings_gs = pd.read_csv(
            csv_url_rating,
            header=0
        )

        ratings_gs = ratings_gs[
            ['Guide', 'MAY RATING GUIDE (1-10)']
        ].copy()

        ratings_gs = ratings_gs.rename(
            columns={
                'Guide': 'Name',
                'MAY RATING GUIDE (1-10)': 'Rating'
            }
        )

        ratings_gs['Rating'] = (
            ratings_gs['Rating'].astype(float)
        )

        guides = pd.merge(
            guides.drop(columns=['Rating']),
            ratings_gs[['Name', 'Rating']],
            on='Name',
            how='left'
        )

        guides['Rating'] = (
            guides['Rating'].fillna(3.0)
        )

        # =====================================================
        # GUIDE DICTIONARY
        # =====================================================

        guides["Unavailability"] = (
            guides["Unavailability"]
            .fillna("")
            .astype(str)
        )

        guide_dict = {}

        for _, row in guides.iterrows():

            unavailable = [
                x.strip()
                for x in row["Unavailability"].split(",")
                if x.strip()
            ]

            guide_dict[row["Name"]] = {
                "rating": float(row["Rating"]),
                "unavailable": unavailable,
                "assigned_count": 0
            }

        # =====================================================
        # ADJ MATRIX
        # =====================================================

        adjacency_records = []

        for _, row in dashboard.iterrows():

            jadwal = row["TANGGAL & RUTE"]
            slot = row["DAY_SHIFT"]

            for guide, info in guide_dict.items():

                available = (
                    slot not in info["unavailable"]
                )

                aij = 1 if available else 0

                adjacency_records.append({
                    "guide": guide,
                    "jadwal": jadwal,
                    "slot": slot,
                    "a_ij": aij
                })

        adj_df = pd.DataFrame(adjacency_records)

        adj_matrix = adj_df.pivot_table(
            index="guide",
            columns="jadwal",
            values="a_ij",
            fill_value=0
        )

        # =====================================================
        # ASSIGNMENT
        # =====================================================

        assignment_output = []

        for guide in guide_dict:
            guide_dict[guide]['assigned_count'] = 0

        for idx, row in dashboard.iterrows():

            jadwal = row["TANGGAL & RUTE"]

            feasible_guides = []

            for guide, info in guide_dict.items():

                aij = adj_matrix.loc[guide, jadwal]

                if aij == 1:

                    rating = info["rating"]
                    k = info["assigned_count"]

                    weight = rating / (k + 1)

                    feasible_guides.append({
                        "guide": guide,
                        "rating": rating,
                        "weight": weight,
                        "k": k
                    })

            if len(feasible_guides) == 0:

                assignment_output.append({
                    "JADWAL": jadwal,
                    "GUIDE_DITUGASKAN": "TIDAK ADA GUIDE",
                    "RATING": None,
                    "k_i": None,
                    "BOBOT": None
                })

                continue

            chosen = max(
                feasible_guides,
                key=lambda x: x["weight"]
            )

            guide_dict[
                chosen["guide"]
            ]["assigned_count"] += 1

            assignment_output.append({
                "JADWAL": jadwal,
                "GUIDE_DITUGASKAN": chosen["guide"],
                "RATING": chosen["rating"],
                "k_i": chosen["k"],
                "BOBOT": round(chosen["weight"], 3)
            })

        assignment_df = pd.DataFrame(
            assignment_output
        )

        # =====================================================
        # EXPORT TO SHEET
        # =====================================================

        spreadsheet = gc.open_by_key(
            SPREADSHEET_ID
        )

        sheet_name_export = "Penugasan"

        try:
            worksheet = spreadsheet.worksheet(
                sheet_name_export
            )

        except:

            worksheet = spreadsheet.add_worksheet(
                title=sheet_name_export,
                rows=1000,
                cols=20
            )

        worksheet.clear()

        set_with_dataframe(
            worksheet=worksheet,
            dataframe=assignment_df,
            include_index=False,
            include_column_header=True,
            resize=True
        )

        return jsonify({
            "status": "success",
            "rows": len(assignment_df)
        })

    except Exception as e:

        return jsonify({
            "status": "error",
            "message": str(e)
        })


if __name__ == "__main__":
    app.run(
        host="0.0.0.0",
        port=8080
    )
```